-- PhotoBooth — initial schema
-- Multi-tenant B2B SaaS. Every tenant-owned row carries studio_id and is isolated by RLS.
-- Tenant resolution: a user's studio membership lives in public.users (id = auth.uid()).

create extension if not exists "pgcrypto";  -- gen_random_uuid()

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type studio_plan      as enum ('free', 'starter', 'studio', 'enterprise');
create type member_role      as enum ('owner', 'admin', 'member');
create type project_status   as enum ('draft', 'previews_uploading', 'awaiting_selection', 'selection_submitted', 'collected', 'archived');
create type selection_status as enum ('in_progress', 'submitted');
create type sub_status       as enum ('trialing', 'active', 'past_due', 'canceled', 'incomplete');

-- ---------------------------------------------------------------------------
-- studios (the tenant)
-- ---------------------------------------------------------------------------
create table public.studios (
  id                   uuid primary key default gen_random_uuid(),
  name                 text not null,
  plan                 studio_plan not null default 'free',
  stripe_customer_id   text unique,
  -- branding for the client-facing gallery
  brand_logo_url       text,
  brand_color          text,
  created_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- users (studio members; id mirrors auth.users.id)
-- ---------------------------------------------------------------------------
create table public.users (
  id          uuid primary key references auth.users(id) on delete cascade,
  studio_id   uuid not null references public.studios(id) on delete cascade,
  email       text not null,
  full_name   text,
  role        member_role not null default 'member',
  created_at  timestamptz not null default now()
);
create index users_studio_id_idx on public.users(studio_id);

-- Helper: the studio_id of the currently authenticated user.
-- SECURITY DEFINER so RLS on public.users doesn't recurse when policies call it.
create or replace function public.current_studio_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select studio_id from public.users where id = auth.uid();
$$;

-- ---------------------------------------------------------------------------
-- projects (one event / shoot)
-- ---------------------------------------------------------------------------
create table public.projects (
  id              uuid primary key default gen_random_uuid(),
  studio_id       uuid not null references public.studios(id) on delete cascade,
  name            text not null,
  client_name     text,
  client_email    text,
  status          project_status not null default 'draft',
  -- opaque token embedded in the client share link; null until shared
  share_token     text unique,
  share_expires_at timestamptz,
  photo_count     integer not null default 0,
  created_at      timestamptz not null default now(),
  created_by      uuid references public.users(id) on delete set null
);
create index projects_studio_id_idx on public.projects(studio_id);
create index projects_share_token_idx on public.projects(share_token);

-- ---------------------------------------------------------------------------
-- photos (one preview record per original image; originals stay on studio's machine)
-- uuid is generated by the desktop app and is the stable cross-system identity.
-- ---------------------------------------------------------------------------
create table public.photos (
  uuid              uuid primary key,
  project_id        uuid not null references public.projects(id) on delete cascade,
  studio_id         uuid not null references public.studios(id) on delete cascade,
  original_filename text not null,
  -- path/key of the preview object in R2 (served via CDN)
  preview_path      text not null,
  content_hash      text,         -- of the original; aids re-collection if files move
  width             integer,
  height            integer,
  taken_at          timestamptz,  -- EXIF capture time, for ordering
  sort_order        integer,
  created_at        timestamptz not null default now()
);
create index photos_project_id_idx on public.photos(project_id);
create index photos_studio_id_idx on public.photos(studio_id);

-- ---------------------------------------------------------------------------
-- selections (client's chosen set for a project)
-- One row per (project, photo) the client picked. Clients are anonymous (no auth);
-- they act through the share token, enforced in Edge Functions, not RLS.
-- ---------------------------------------------------------------------------
create table public.selections (
  id          uuid primary key default gen_random_uuid(),
  project_id  uuid not null references public.projects(id) on delete cascade,
  studio_id   uuid not null references public.studios(id) on delete cascade,
  photo_uuid  uuid not null references public.photos(uuid) on delete cascade,
  status      selection_status not null default 'submitted',
  created_at  timestamptz not null default now(),
  unique (project_id, photo_uuid)
);
create index selections_project_id_idx on public.selections(project_id);

-- ---------------------------------------------------------------------------
-- subscriptions (mirror of Stripe state for entitlement checks)
-- ---------------------------------------------------------------------------
create table public.subscriptions (
  studio_id              uuid primary key references public.studios(id) on delete cascade,
  stripe_subscription_id text unique,
  plan                   studio_plan not null default 'free',
  status                 sub_status not null default 'trialing',
  current_period_end     timestamptz,
  updated_at             timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security — tenant isolation on studio_id
-- ---------------------------------------------------------------------------
alter table public.studios       enable row level security;
alter table public.users         enable row level security;
alter table public.projects      enable row level security;
alter table public.photos        enable row level security;
alter table public.selections    enable row level security;
alter table public.subscriptions enable row level security;

-- studios: members can see and update their own studio
create policy studios_select on public.studios
  for select using (id = public.current_studio_id());
create policy studios_update on public.studios
  for update using (id = public.current_studio_id());

-- users: members can see co-members of their studio; can update their own row
create policy users_select on public.users
  for select using (studio_id = public.current_studio_id());
create policy users_update_self on public.users
  for update using (id = auth.uid());

-- projects / photos / selections / subscriptions: full access scoped to own studio
create policy projects_all on public.projects
  for all using (studio_id = public.current_studio_id())
  with check (studio_id = public.current_studio_id());

create policy photos_all on public.photos
  for all using (studio_id = public.current_studio_id())
  with check (studio_id = public.current_studio_id());

create policy selections_all on public.selections
  for all using (studio_id = public.current_studio_id())
  with check (studio_id = public.current_studio_id());

create policy subscriptions_select on public.subscriptions
  for select using (studio_id = public.current_studio_id());

-- Note: anonymous client gallery access (browsing previews + submitting selections via a
-- share token) is intentionally NOT exposed through RLS. It is handled by Edge Functions
-- using the service-role key after validating projects.share_token / share_expires_at.
